In [ ]:
from sklearn import datasets

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import SGDClassifier

import pandas as pd
import numpy as np


In [ ]:
iris = datasets.load_iris()

In [ ]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
X = iris['data']
Y = iris['target']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8)

In [ ]:
log_clf = LogisticRegression(max_iter=1000)
log_clf.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
log_pred  = log_clf.predict(X_test)

In [ ]:
log_pred


array([2, 2, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2, 0, 0, 2, 2, 1, 0, 2, 2, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1])

In [ ]:
Y_test

array([2, 2, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2, 0, 0, 2, 2, 1, 0, 2, 2, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1])

In [ ]:
log_clf.predict_proba(X_test)

array([[4.58159850e-06, 3.19921285e-02, 9.68003290e-01],
       [1.00158437e-05, 6.42021489e-02, 9.35787835e-01],
       [9.67022687e-01, 3.29770014e-02, 3.11717755e-07],
       [6.76313222e-04, 3.61316425e-01, 6.38007261e-01],
       [9.69996531e-01, 3.00034187e-02, 5.04820700e-08],
       [1.77296373e-01, 8.18779914e-01, 3.92371361e-03],
       [7.30228622e-08, 6.58778379e-03, 9.93412143e-01],
       [9.77369099e-01, 2.26308638e-02, 3.70221541e-08],
       [1.41193417e-03, 3.93345819e-01, 6.05242247e-01],
       [1.85147051e-02, 8.86743039e-01, 9.47422558e-02],
       [1.20128625e-02, 9.71198633e-01, 1.67885044e-02],
       [3.52809911e-05, 7.64071735e-02, 9.23557545e-01],
       [9.81701123e-01, 1.82988456e-02, 3.11127138e-08],
       [9.83205679e-01, 1.67942914e-02, 2.94618949e-08],
       [3.85509424e-04, 1.75271042e-01, 8.24343449e-01],
       [7.60880704e-04, 4.84078705e-01, 5.15160414e-01],
       [1.05278576e-02, 9.26764740e-01, 6.27074022e-02],
       [9.83658466e-01, 1.63415

In [ ]:
sgd_clf = SGDClassifier(loss='log')
sgd_clf.fit(X_train ,Y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l2', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [ ]:
sgd_predict = sgd_clf.predict(X_test)
sgd_predict

array([1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 2, 1, 1, 0, 2, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1])

In [ ]:
log_prab = sgd_clf.predict_log_proba(X_test)
log_prab

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:1068: RuntimeWarning: divide by zero encountered in log
  return np.log(self.predict_proba(X))


array([[-5.54856316e+01, -2.10942375e-15, -3.37479771e+01],
       [-6.55235825e+01, -6.92792105e-01, -6.93502383e-01],
       [ 0.00000000e+00, -9.11878060e+01,            -inf],
       [-4.87628114e+01,  0.00000000e+00, -7.33533493e+01],
       [ 0.00000000e+00, -6.86532416e+01,            -inf],
       [-1.46505738e+01, -4.33847129e-07, -2.93897681e+02],
       [-7.71270706e+01, -6.93147181e-01, -6.93147181e-01],
       [ 0.00000000e+00, -5.99382461e+01,            -inf],
       [-1.46342962e+01, -4.40966913e-07, -9.73442708e+01],
       [-8.05804788e-02, -2.55851856e+00, -2.37905910e+02],
       [-2.68420367e+01, -2.20112817e-12, -2.95271981e+02],
       [-2.97698248e+01, -1.17905685e-13, -4.43773808e+01],
       [ 0.00000000e+00, -6.94209898e+01,            -inf],
       [ 0.00000000e+00, -7.42413518e+01,            -inf],
       [-4.98998017e+01, -5.53158986e+00, -3.96754907e-03],
       [-4.48424730e+01,  0.00000000e+00, -1.38482140e+02],
       [-2.47835665e+01, -1.72438730e-11

In [ ]:
proba = sgd_clf.predict_proba(X_test)
proba

array([[7.99643460e-025, 1.00000000e+000, 2.20515831e-015],
       [3.49518096e-029, 5.00177569e-001, 4.99822431e-001],
       [1.00000000e+000, 2.49826797e-040, 0.00000000e+000],
       [6.64630243e-022, 1.00000000e+000, 1.39009716e-032],
       [1.00000000e+000, 1.52853719e-030, 0.00000000e+000],
       [4.33847035e-007, 9.99999566e-001, 2.30069357e-128],
       [3.19255839e-034, 5.00000000e-001, 5.00000000e-001],
       [1.00000000e+000, 9.31430561e-027, 0.00000000e+000],
       [4.40966816e-007, 9.99999559e-001, 5.29566295e-043],
       [9.22580652e-001, 7.74193476e-002, 4.77283131e-104],
       [2.20115977e-012, 1.00000000e+000, 5.82113878e-129],
       [1.17795683e-013, 1.00000000e+000, 5.33517152e-020],
       [1.00000000e+000, 7.09328129e-031, 0.00000000e+000],
       [1.00000000e+000, 5.71992803e-033, 0.00000000e+000],
       [2.13202098e-022, 3.95968874e-003, 9.96040311e-001],
       [3.35089976e-020, 1.00000000e+000, 7.21058645e-061],
       [1.72438334e-011, 1.00000000e+000